### ISSUE TITLE
SSIS Connections Not Found in Analyzer - Project Connections

### ISSUE THREAD

**Issue by fujimoh** [keif888/SQLServerMetadata#15] opened 2018-02-08 00:20 UTC
When a Project Connection is Used, analyzing the package fails with the following error.

Loading file package 'XXXXXXXXXXXX.dtsx'... Error occurred: 'The connection "{4EC7FAD8-B346-4C08-830D-5470BED82476}" is not found. This error is thrown by Connections collection when the specific connection element is not found.  

I can confirm that the *.conmgr files exist in the directory.

Analyzer moves on to other packages and completes those successfully when they dod not use Project Connections.

I am encountering the exact same issue when using SQL against the XML since the connection in not referenced in the package except through the object that references it.  I think there needs to be a subprocess that examines connections referenced in the objects then enumerating the directory for conmgr files for the properties.

**Comment by fmms** [comment] 2018-02-08 06:33
Hi @fujimoh the package modell at the moment just works for reading from SSISDB and not from the file system. See @keif888 comment https://github.com/keif888/SQLServerMetadata/issues/4#issuecomment-362805910 . Can you try to deploy you project to SSISDB and read from there?

**Comment by keif888** [comment] 2018-02-08 12:31
This is a duplicate of issue #4.  

Closing as dtsx files on the file system will be handled in that issue when fixed.

**Closed as completed by keif888** 2018-02-08 12:31 UTC
Labels: duplicate
